name: General Checks

on:
  pull_request:
    branches:
      - master
      - develop
  schedule:
    - cron:  '0 11,12,13,14,15,16,17 * * 1,2,3,4,5'

jobs:
  GeneralChecks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup java v11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: initialize db
        run: docker run -p 5432:5432 --name db-container -e POSTGRES_PASSWORD=123 -d postgres
      - name: Run Tests with Gradle
        run: gradle check
